services:
  - type: web
    name: mentormatch-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn mentormatch_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: mentormatch_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mentormatch-db
          property: connectionString
    
databases:
  - name: mentormatch-db
    databaseName: mentormatch
    user: mentormatch
    region: oregon
