services:
  - type: web
    name: mentormatch-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd mentormatch_backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      cd mentormatch_backend
      gunicorn mentormatch_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: mentormatch_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mentormatch-db
          property: connectionString

databases:
  - name: mentormatch-db
    plan: free
    databaseName: mentormatch
    user: mentormatch
    region: oregon